name: Build/test package

on:
    workflow_dispatch:
    push:

jobs:
    linux:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10"]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: Lint with black and flake8
              run: |
                  black .
                  flake8 . --show-source --statistics
            - name: Test with pytest
              run: |
                  pytest
